-- Feedback system redesign: add metadata fields, upvotes, and broaden transparency

-- 1) Add new columns for feedback metadata
ALTER TABLE public.feedback_reports
  ADD COLUMN IF NOT EXISTS feedback_number bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS module text,
  ADD COLUMN IF NOT EXISTS priority text,
  ADD COLUMN IF NOT EXISTS upvotes integer NOT NULL DEFAULT 0;

-- 2) Backfill feedback numbers for existing rows
UPDATE public.feedback_reports
SET feedback_number = nextval('public.feedback_reports_feedback_number_seq')
WHERE feedback_number IS NULL;

-- 3) Ensure feedback numbers are unique
ALTER TABLE public.feedback_reports
  ADD CONSTRAINT feedback_reports_feedback_number_key UNIQUE (feedback_number);

-- 4) Update status constraint to new lifecycle
ALTER TABLE public.feedback_reports
  DROP CONSTRAINT IF EXISTS feedback_reports_status_check;

-- Normalize legacy status values before applying new constraint
UPDATE public.feedback_reports
SET status = 'in_progress'
WHERE status = 'in_review';

ALTER TABLE public.feedback_reports
  ADD CONSTRAINT feedback_reports_status_check
  CHECK (status IN ('open', 'in_progress', 'resolved', 'closed'));

-- 5) Add priority constraint for clarity
ALTER TABLE public.feedback_reports
  DROP CONSTRAINT IF EXISTS feedback_reports_priority_check;

ALTER TABLE public.feedback_reports
  ADD CONSTRAINT feedback_reports_priority_check
  CHECK (priority IS NULL OR priority IN ('low', 'medium', 'high', 'critical'));

-- 6) Create feedback_upvotes table
CREATE TABLE IF NOT EXISTS public.feedback_upvotes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  feedback_id uuid NOT NULL REFERENCES public.feedback_reports(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (feedback_id, user_id)
);

ALTER TABLE public.feedback_upvotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view upvotes" ON public.feedback_upvotes;
DROP POLICY IF EXISTS "Authenticated users can upvote" ON public.feedback_upvotes;
DROP POLICY IF EXISTS "Authenticated users can remove their upvote" ON public.feedback_upvotes;

CREATE POLICY "Authenticated users can view upvotes"
  ON public.feedback_upvotes FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can upvote"
  ON public.feedback_upvotes FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Authenticated users can remove their upvote" ON public.feedback_upvotes;
CREATE POLICY "Authenticated users can remove their upvote"
  ON public.feedback_upvotes FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- 7) Update feedback_reports RLS policies for internal transparency
DROP POLICY IF EXISTS "Users can view own feedback" ON public.feedback_reports;
DROP POLICY IF EXISTS "Admins can view all feedback" ON public.feedback_reports;
DROP POLICY IF EXISTS "Admins can update feedback" ON public.feedback_reports;

DROP POLICY IF EXISTS "All authenticated users can view feedback" ON public.feedback_reports;
CREATE POLICY "All authenticated users can view feedback"
  ON public.feedback_reports FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL);

DROP POLICY IF EXISTS "All authenticated users can update feedback" ON public.feedback_reports;
CREATE POLICY "All authenticated users can update feedback"
  ON public.feedback_reports FOR UPDATE
  TO authenticated
  USING (deleted_at IS NULL)
  WITH CHECK (deleted_at IS NULL);

DROP POLICY IF EXISTS "Only super admin can delete feedback" ON public.feedback_reports;
CREATE POLICY "Only super admin can delete feedback"
  ON public.feedback_reports FOR DELETE
  TO authenticated
  USING (has_role(auth.uid(), 'super_admin'::app_role));

-- 8) Update feedback_comments RLS policies for shared visibility
DROP POLICY IF EXISTS "Users can view comments on own feedback" ON public.feedback_comments;
DROP POLICY IF EXISTS "Users can comment on own feedback" ON public.feedback_comments;

DROP POLICY IF EXISTS "All authenticated users can view comments" ON public.feedback_comments;
CREATE POLICY "All authenticated users can view comments"
  ON public.feedback_comments FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "All authenticated users can add comments" ON public.feedback_comments;
CREATE POLICY "All authenticated users can add comments"
  ON public.feedback_comments FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());
